/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class Task1 {

	public static void main(String[] args)
	{
		Task1 t1 = new Task1();
		t1.test1()
	}

	public boolean test1() {
		println "I am test1 in Task1"
	}

}


